<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not put any code except 'define' operations
 * as it could be overwritten.
 * Instead, use the Mouf User Interface to set all your constants: http://[server]/sandbox/quiz-demo-splash/vendor/mouf/mouf/mouf/config
 */

define('SECRET', 'fds56fsd46f4sd56f4sd');
define('DEBUG', true);
